### ISSUE TITLE
Case sensitive identifer search

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_new_webservices#18]
This works:
https://wwwdev.ebi.ac.uk/chembl/api/data/molecule/CHEMBL25

But this does not:
https://wwwdev.ebi.ac.uk/chembl/api/data/molecule/chembl25

**Comment by mnowotka** [comment]
The latter is not a valid ChEMBL identifier :)

**Comment by mark-davies** [comment]
Very true

**Comment by mnowotka** [comment]
Fixed.

**Comment by mark-davies** [comment]
Tested and working
