### ISSUE TITLE
-1 values in some fields after sim search ws call

### ISSUE THREAD

**Issue by madgpap** [chembl/chembl_new_webservices#23]
![image](https://cloud.githubusercontent.com/assets/3305715/5742938/b05d7330-9c0d-11e4-8265-b3f66895e515.png)

**Comment by mnowotka** [comment]
I don't understand why you think this is a bug. Please see "ChEMBL Web Service Review" document (in google docs, made by Mark) and see example data of molecule resource. You will see availability_type=1 because this is what we have stored in ChEMBL.
