### ISSUE TITLE
Filter and format args included in next/prev links

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_new_webservices#3]
When the following search is conducted:  /new_chemblws/target?pref_name__contains=kinase&format=json, the format and filter are not included in the next/prev links: 

"page_meta": {

    "limit": 20,
    "next": "/new_chemblws/target?limit=20&offset=20",
    "offset": 0,
    "previous": null,
    "total_count": 746

},

**Comment by mnowotka** [comment]
Fixed.

**Comment by mark-davies** [comment]
Tested and working
