### ISSUE TITLE
Add HELM notation to biotherapeutics 

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_new_webservices#31]
New in ChEMBL_20 and found in the biotherapeutics table

**Comment by madgpap** [comment]
yey

**Comment by mnowotka** [comment]
Done.

**Comment by mark-davies** [comment]
Tested and working.

https://wwwdev.ebi.ac.uk/chembl/api/data/molecule?helm_notation__isnull=false returns a total count of 18971, which corresponds to count in database. 

I will leave open for bit longer so that Anna and George can comment if necessary.

**Comment by agaulton** [comment]
Looks good to me!
