### ISSUE TITLE
Add ATC to molecule endpoint

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_new_webservices#32]
Add a new ATC section to the molecule endpoint, example section would look like:
```
....
<atc_classifications>
  <level5>D05AX05</level5>
  <level5>D05BA01</level5>
</atc_classifications>
....
```

Note that 1 molecule can have multiple atc_classifications, as in example above

The data comes from the molecule_atc_classification table.

**Comment by mnowotka** [comment]
Done, please verify.

**Comment by mark-davies** [comment]
Working very nicely. 

Using ChEMBL 20, the following request returns 50 results:

https://www.ebi.ac.uk/chembl/api/data/molecule?atc_classifications__level5__startswith=A10 returns 50 

the same as the equivalent SQL:

SELECT COUNT(DISTINCT md.chembl_id)
FROM molecule_atc_classification mac,
molecule_dictionary md
WHERE mac.molregno=md.molregno
AND mac.level5 LIKE 'A10%';
