### ISSUE TITLE
Target Component Update

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_new_webservices#33]
It would make sense to remove the target component ids from the web services, as they are used to handle the many-2-many relationship between targets and component sequences. End users do not need to see this. 

The current target endpoint looks like:

```
<?xml version="1.0"?>
<target>
  <organism>Homo sapiens</organism>
  <pref_name>Cyclin-dependent kinase 2/cyclin E</pref_name>
  <species_group_flag/>
  <target_chembl_id>CHEMBL2094126</target_chembl_id>
  <target_components>
    <target_component>
      <target_component_id>6531</target_component_id>
    </target_component>
    <target_component>
      <target_component_id>6532</target_component_id>
    </target_component>
    <target_component>
      <target_component_id>6533</target_component_id>
    </target_component>
  </target_components>
  <target_type>PROTEIN COMPLEX</target_type>
</target>
```

And the an example target_component looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<target_component>
  <component>
    <accession>P24864</accession>
    <component_id>35</component_id>
    <component_type>PROTEIN</component_type>
    <description>G1/S-specific cyclin-E1</description>
    <organism>Homo sapiens</organism>
    <protein_classifications>
      <protein_classification>
        <protein_classification_id>8</protein_classification_id>
      </protein_classification>
    </protein_classifications>
   <sequence>MPRERRERDAKERDTMKEDGGAEFSARSRKRKANVTVFLQDPDEEMAKIDRTARDQCGSQPWDNNAVCADPCSLIPTPDKEDDDRVYPNSTCKPRIIAPSRGSPLPVLSWANREEVWKIMLNKEKTYLRDQHFLEQHPLLQPKMRAILLDWLMEVCEVYKLHRETFYLAQDFFDRYMATQENVVKTLLQLIGISSLFIAAKLEEIYPPKLHQFAYVTDGACSGDEILTMELMIMKALKWRLSPLTIVSWLNVYMQVAYLNDLHEVLLPQYPQQIFIQIAELLDLCVLDVDCLEFPYGILAASALYHFSSSELMQKVSGYQWCDIENCVKWMVPFAMVIRETGSSKLKHFRGVADEDAHNIQTHRDSLDLLDKARAKKAMLSEQNRASPLPSGLLTPPQSGKKQSSGPEMA</sequence>
    <tax_id>9606</tax_id>
  </component>
  <targcomp_id>6531</targcomp_id>
</target_component>
```

I suggest we change the target end point to look like:

```
<?xml version="1.0"?>
<target>
  <organism>Homo sapiens</organism>
  <pref_name>Cyclin-dependent kinase 2/cyclin E</pref_name>
  <species_group_flag/>
  <target_chembl_id>CHEMBL2094126</target_chembl_id>
  <target_components>
    <component>
      <accession>P24864</accession>
      <component_id>35</component_id>
      <component_type>PROTEIN</component_type>
    </component>
    <component>
      <accession>P24941</accession>
      <component_id>36</component_id>
      <component_type>PROTEIN</component_type>
    </component>
    <component>
      <accession>O96020</accession>
      <component_id>1213</component_id>
      <component_type>PROTEIN</component_type>
    </component>
  </target_components>
  <target_type>PROTEIN COMPLEX</target_type>
</target>
```

The target_component endpoint would be a list of distinct components (e.g. select * from component sequences) and the targcomp_id would be removed.

Considerations:
1. We should be able to search the target endpoint by accession
2. Should some of the attribute names be renamed? Users familiar with the relational schema might think the component_id is the targcomp_id
3. Should the target_component endpoint be renamed components? Again might be confusing to users who are familiar with the schema
4. In the future we may add additional information to the new component block, e.g. relationship and homologue, which are currently captured in the assays table.
5. Should we add more/all component attributes to the target component block?

**Comment by mnowotka** [comment]
Can you give an example of `target_component` after the change?

**Comment by mark-davies** [comment]
Sure, it will look very similar to the current target_component endpoint, see below for an example:

```
  <target_components>
      <component>
        <accession>P89449</accession>
        <component_id>1738</component_id>
        <component_type>PROTEIN</component_type>
        <description>Capsid scaffolding protein</description>
        <organism>Human herpesvirus 2 (strain HG52) (HHV-2) (Human herpes simplex virus2)</organism>
        <protein_classifications>
          <protein_classification>
            <protein_classification_id>27</protein_classification_id>
          </protein_classification>
        </protein_classifications>
        <sequence>MASAEMRERLEAPLPDRAVPIYVAGFLAL..........</sequence>
        <tax_id>10315</tax_id>
      </component>
      <component>
        <accession>Q01237</accession>
        <component_id>1097</component_id>
        <component_type>PROTEIN</component_type>
        <description>3-hydroxy-3-methylglutaryl-coenzyme A reductase</description>
        <organism>Mus musculus</organism>
        <protein_classifications>
          <protein_classification>
            <protein_classification_id>1</protein_classification_id>
          </protein_classification>
        </protein_classifications>
        <sequence>MLSRLFRMHGLFVASHPWEVI..........</sequence>
        <tax_id>10090</tax_id>
      </component>
....
</target_components>
```

**Comment by mnowotka** [comment]
I can't find any difference between old and new `target_component` resource. I understand what needs to be done in `target` but not in `target_component`.

**Comment by mnowotka** [comment]
I mean, when I remove `targcomp_id`, how the `target_component` will be accessed?

**Comment by mark-davies** [comment]
There will be some redundancy in the current target_component endpoint. For example the component_id 79 appears 13 times in the current target_componets table:

select * from target_components where component_id =79;

which we want to remove from the target_component endpoint, some example target_components with the same component_id:

https://www.ebi.ac.uk/chembl/api/data/target_component/6027
https://www.ebi.ac.uk/chembl/api/data/target_component/6257
....

So there should only be 1 entry for component_id 79 in the target_component endpoint

**Comment by mnowotka** [comment]
OK, but 6027 or 6257 is targcomp_id so if we are using it to access target_component resource why removing it from there when all other resources have their IDs included?

**Comment by mnowotka** [comment]
This is now fixed, but please, verify this carefully.
