### ISSUE TITLE
new columns/fields in activity ws

### ISSUE THREAD

**Issue by madgpap** [chembl/chembl_new_webservices#34]
Can we add target name and organism, assay type and description and reference in the response retrieved by an activity ws call?
These are very useful. 
On the other hand, record_id, BAO endpoint, qudt units, uo_units are less important for the average user. 

e.g.
https://www.ebi.ac.uk/chembl/api/data/activity?limit=1000&molecule_chembl_id=CHEMBL482538

**Comment by mark-davies** [comment]
This should be a problem as we already select some data those relations, so we should already being paying the cost for the join.

**Comment by mnowotka** [comment]
OK, but I need a proper example of how the modified resource should look like.

**Comment by madgpap** [comment]
the same resource with the additional fields mentioned above, as per the old activity chemblws:
https://www.ebi.ac.uk/chemblws/compounds/CHEMBL2/bioactivities
<reference>J. Med. Chem., (2003) 46:2:265</reference>
<assay_type>B</assay_type>
<target_name>Dopamine D1 receptor</target_name>
<organism>Rattus norvegicus</organism>
<assay_description>
Ability to displace [3H]-SCH- 23390 (0.2 nM) from corpus striatum of rat Dopamine receptor D1
</assay_description>

**Comment by mark-davies** [comment]
How about the following new attributes to be added to the activity endpoints:
```
<assay_type>B</assay_type>
<assay_description>Evaluated for its activity to inhibit rat liver 2,3-oxidosqualene-lanosterol cyclase, activity expressed as Ki</assay_description>
<target_organism>Homo sapiens</target_organism>
<target_pref_name>Lanosterol synthase</target_pref_name>
```

I am not a big fan of formatted article sting, would the following 2 attributes be enough:
```
<document_year>1994</document_year>
<document_journal>Bioorg. Med. Chem. Lett.</document_journal>
```

**Comment by mnowotka** [comment]
Agree, I would like to keep values from separate DB columns in separate attributes.

**Comment by madgpap** [comment]
cool - no probs with that.

**Comment by mnowotka** [comment]
OK, I did some performance tests and I would prefer to close this issue with `wont_fix` resolution. It is not true, that we are already paying costs of joins:

   *  This is the first time we refer to Docs
   * This is the first time we refer to Assays (previously we had only assay_chembl_id) which is a part of Activities table
   * This is the first time we refer to Target (previously we had only target_chembl_id) which is a part of Activities table

This slows this resource completely, my tests are 1/3 times slower and testing Activities is only a small part.

We can't put everything in one resource, this is why we have other resources (Documents, Targets, Assays). It is nice to be nice but IMO this time the price is to high.

**Comment by mnowotka** [comment]
Hmm, actually `assay_chembl_id` and `target_chembl_id` are not included in Activities table, still the performance penalty is the fact.

**Comment by madgpap** [comment]
there is also ```document_chembl_id``` in the response

**Comment by mnowotka** [comment]
Yep, I'm investigating this.

**Comment by madgpap** [comment]
The performance penalty will be paid by the user further down the work flow, when they try to fetch docs, assay and target information for the activity data

**Comment by madgpap** [comment]
For the record, I disagree with the proposed ```wont_fix``` resolution and I would choose convenience over performance. 
Happy to discuss further tomorrow. :)

**Comment by mnowotka** [comment]
With that thinking downloading SQL dump from FTP has the lowest penalty.

**Comment by mnowotka** [comment]
But!!!
It's OK now, I had regression in code, no worries it will be done :)

**Comment by madgpap** [comment]
![image](https://cloud.githubusercontent.com/assets/3305715/6109236/80f7012e-b071-11e4-83cc-587d8f0c26f9.png)

**Comment by mnowotka** [comment]
Done, but please check.

**Comment by madgpap** [comment]
It is beautiful - thanks.

![image](https://cloud.githubusercontent.com/assets/3305715/6166991/e55f0470-b2ad-11e4-97e7-6435cd81d323.png)
