### ISSUE TITLE
add string input to POST image2ctab, image2smiles

### ISSUE THREAD

**Issue by madgpap** [chembl/chembl_new_webservices#37]
as discussed on Skype - it would be nice if the image POST methods could accept a base64 string, in addition to binary data. 
This is for the KNIME use case, reported in the web services manuscript.

**Comment by mnowotka** [comment]
Dear George,

String input was always supported. Please take a look at the following code:

    img = request.body.read()
    if img.startswith('data:'):
        img = base64.b64decode(img[img.find(',')+1:])

Which means that, whatever you submit will be treated like string if it starts with 'data' in case of png you should start your string with `data:image/png;base64,` and that's all.

But I agree that this should be documented.

**Comment by madgpap** [comment]
![image](https://cloud.githubusercontent.com/assets/3305715/6168404/0284648c-b2bd-11e4-8622-c33a142d553d.png)
