### ISSUE TITLE
Add a document endpoint to new web services

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_new_webservices#6]

**Comment by mnowotka** [comment]
Done: http://ves-ebi-56.ebi.ac.uk:8690/chembl/chembl_webservices/new_chemblws/docs
As you see the base url of the webservices has changed (as I put them behind Apache) and now it's:

http://ves-ebi-56.ebi.ac.uk:8690/chembl/chembl_webservices/new_chemblws

**Comment by mark-davies** [comment]
Tested and working - very nice
