### ISSUE TITLE
Substructure search should require parameter

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_new_webservices#8]
http://ves-ebi-56.ebi.ac.uk:9796/new_chemblws/substructure should require user to provide parameter, same as similarity search (e.g. http://ves-ebi-56.ebi.ac.uk:9796/new_chemblws/similarity). Currently call to URL above returns following error: More than 'MoleculeDictionary' matched ''.

**Comment by mnowotka** [comment]
Fixed.

**Comment by mnowotka** [comment]
Now fixed for substructure, similarity and images.

**Comment by mark-davies** [comment]
Tested and working
